### PR TITLE
Don't hardcode python paths

### PR DESCRIPTION
**Pull request by JL2210**
Fix `/usr/bin/python3: bad interpreter: No such file or directory` error

### CODE REVIEW

**Comment by superm1** [comment]
It's a tough decision which is more correct.  See this blog post for some example in why:
https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/

I'd ask - what environment are you trying to run libsmbios in and encountering this problem?

**Comment by JL2210** [comment]
A Dell Chromebook in Developer Mode.

**Comment by superm1** [comment]
Dell Chromebooks won't have the proper support for libsmbios no matter what OS you have loaded.

**Comment by JL2210** [comment]
@superm1 This would also apply to Dell laptops running Chromium OS.

**Pull request closed without merging**
